POST http://localhost:3000/subscribers/create
Content-Type: application/json

{
    "name":"a",
    "subscribedTo":"Krishna"
}

###
GET http://localhost:3000/subscribers
###
GET http://localhost:3000/subscribers/5f72ef643630c4018d74d116

###
PATCH http://localhost:3000/subscribers/update/5f72ef643630c4018d74d116
Content-Type: application/json

{
    "name" : "New Name",
    "subscribedTo": "Me"
}

###
DELETE http://localhost:3000/subscribers/delete/5f72ef643630c4018d74d116

